services:
  liar:
    image: ghcr.io/arman511/rguhack26
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      default:
        aliases:
          - liar
networks:
  default:
    name: zoraxy_proxy
    external: true
